#!/usr/bin/env bash

# This script uses the centurylink/golang-builder docker image
# to build and statically link the Go application within this
# directory.

# https://github.com/CenturyLinkLabs/golang-builder

docker run --rm \
	-v "$(pwd)":/src \
	centurylink/golang-builder


